name: CI

# Controls when the workflow will run
on:
  schedule:
    - cron: "13 21 * * *"
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    environment: ntfy secret
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: make demo curl
        env:
          NTFY_TOPIC: ${{ secrets.NTFY_TOPIC }}
        run: |
          REF_HASH=$(cat e_bbcs_supporting-documentprovedequipment.pdf | sha256sum)
          URL="https://www.swisscom.ch/content/dam/swisscom/en/ws/documents/E_BBCS-Documents/e_bbcs_supporting-documentprovedequipment.pdf"
          PDF_HASH=$(curl "$URL" | sha256sum)
          [ "$PDF_HASH" != "$REF_HASH" ] && curl -d "new update to router list: $URL" ntfy.sh/"$NTFY_TOPIC" > /dev/null || echo "pdf is unchanged"
